export {
    Camera,
    Play,
    StopCircle,
    Users,
    BarChart3,
    Clock,
    CheckCircle,
    AlertCircle,
    X,
    User,
    Shield,
    QrCode,
    Eye,
    EyeOff,
    TrendingUp,
    Calendar,
    DollarSign,
    FileSpreadsheet,
    Download,
    Plus,
    Settings,
    Lock,
    Unlock,
    UserPlus,
    FolderPlus,
    FolderX,
    Edit,
    Trash2,
    Ban,
    Check,
    LogOut,
    Menu,
    Building2,
    // FIX: Add missing ArrowLeftRight icon to exports.
    ArrowLeftRight
} from 'lucide-react';